### Create a new user
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "nehi@example.com",
  "username": "nehi",
  "password": "nehi"
}

### Get all users
GET http://localhost:3000/user

### Get a user by ID
GET http://localhost:3000/user/e478720a-ff08-4c02-8fd4-aa59fdfdde8e

### Update a user548843d9-ad42-41b6-ae2a-e7b509dc216c
PATCH http://localhost:3000/user/e478720a-ff08-4c02-8fd4-aa59fdfdde8e
Content-Type: application/json

{
  "email": "nehirugue@gmai.come"
}

### Delete a user
DELETE http://localhost:3000/user/548843d9-ad42-41b6-ae2a-e7b509dc216c

### Create a new task
POST http://localhost:3000/task
Content-Type: application/json

{
  "title": "New Task",
  "description": "Task description",
  "dueDate": "2024-11-30T23:59:59.999Z",
  "status": "pending",
  "priority": "high",
  "createdBy": "cd219f1c-d56a-4e7c-b138-b31e3220f741",
  "assignedTo": "assignee@example.com",
  "tags": ["work", "urgent"]
}

### Get all tasks
GET http://localhost:3000/task

### Get a task by ID
GET http://localhost:3000/task/610f927b-e819-4350-8ff7-40e73b16d8d1

### Update a task
PUT http://localhost:3000/task/610f927b-e819-4350-8ff7-40e73b16d8d1
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "Updated description",
  "dueDate": "2024-01-31",
  "status": "in-progress",
  "priority": "medium",
  "assignedTo": "updatedassignee@example.com",
  "tags": ["update", "important"]
}

### Delete a task
DELETE http://localhost:3000/task/610f927b-e819-4350-8ff7-40e73b16d8d1
